name: Sample Workflow
on:
  workflow_dispatch: 

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - run: echo Hello World!
      - run: whoami
      - run: pwd
      - run: env
      - run: printenv
